USE bus_transportation;

DROP TABLE route, bus, driver, bus_driver;

CREATE TABLE route(ROUTE_NO INT PRIMARY KEY, SOURCE VARCHAR(20), DESTINATION VARCHAR(20), NO_OF_STATIONS INT);

CREATE TABLE bus(BUS_NO INT PRIMARY KEY, ROUTE_NO INT, FOREIGN KEY (ROUTE_NO) REFERENCES route(ROUTE_NO), CAPACITY INT, DEPOT_NAME VARCHAR(20));

CREATE TABLE driver(DRIVER_NO INT PRIMARY KEY, DRIVER_NAME VARCHAR(20), LICENSE_NO INT, ADDRESS VARCHAR(20), D_AGE INT, SALARY FLOAT);

CREATE TABLE bus_driver(DRIVER_NO INT, FOREIGN KEY (DRIVER_NO) REFERENCES driver(DRIVER_NO), BUS_NO INT, FOREIGN KEY (BUS_NO) REFERENCES bus(BUS_NO), DATE_OF_DUTY DATE, SHIFT VARCHAR(10));

