USE mobile_billing;

DROP TABLES plan, customer, cust_call_info, bill;

CREATE TABLE plan(PLAN_NO INT PRIMARY KEY, PNAME VARCHAR(20), NO_OF_FREE_CALLS INT, REATE_PER_CALL_MIN DOUBLE, FREE_CALL_TIME INT, FIXED_AMT DOUBLE);

CREATE TABLE customer(CUST_NO INT PRIMARY KEY, PLAN_NO INT, FOREIGN KEY (PLAN_NO) REFERENCES plan(PLAN_NO), NAME VARCHAR(20), MOBILE_NO VARCHAR(10));

CREATE TABLE cust_call_info(REC_NO INT PRIMARY KEY, CUST_NO INT, FOREIGN KEY (CUST_NO) REFERENCES customer(CUST_NO), NO_OF_CALLS INT, TOTAL_TALK_TIME INT, CYCLE_PERIOD VARCHAR(20));

CREATE TABLE bill(REC_NO INT,  FOREIGN KEY (REC_NO) REFERENCES cust_call_info(REC_NO), BILL_NO INT PRIMARY KEY, CUST_NO INT, FOREIGN KEY (CUST_NO) REFERENCES customer(CUST_NO),FINAL_BILL_AMT DOUBLE, CYCLE_DATE DATE, BILL_DUE_DATE DATE, STATUS VARCHAR(10), BILL_PAY_DATE DATE);

