USE railway_reservation;

DROP TABLES train, passenger, ticket, train_passenger;

CREATE TABLE train(TRAIN_NO INT PRIMARY KEY, TRAIN_NAME VARCHAR(20), DEPART_TIME TIME, ARRIVAL_TIME TIME, SOURCE_STN VARCHAR(20), DEST_STN VARCHAR(20), NO_OF_RES_BOGIES INT, BOGIE_CAPACITY INT);

CREATE TABLE passenger(PASSENGER_ID INT PRIMARY KEY, PASSENGER_NAME VARCHAR(20), ADDRESS VARCHAR(30), AGE INT, GENDER VARCHAR(10));

CREATE TABLE ticket(TRAIN_NO INT, FOREIGN KEY (TRAIN_NO) REFERENCES train(TRAIN_NO), PASSENGER_ID INT, FOREIGN KEY (PASSENGER_ID) REFERENCES passenger(PASSENGER_ID), TICKET_NO INT,  BOGIE_NO INT, NO_OF_BERTHS INT, DATE_OF_TRAVEL DATE, TICKET_AMT DECIMAL, STATUS VARCHAR(30));

CREATE TABLE train_passenger(TRAIN_NO INT, FOREIGN KEY (TRAIN_NO) REFERENCES train(TRAIN_NO), PASSENGER_ID INT, FOREIGN KEY (PASSENGER_ID) REFERENCES passenger(PASSENGER_ID));